[tool.black]
line-length = 88
target = 3.8
include = '\*.pyi?$'
exclude = '''
/(
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \venv
  | \.venv
  | \.orch-venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
)/
'''
